export class Prestation {
    id_prestation;
    no_contrat;
    id_pilot;
    departement;
    pole;
    domaine;
    code_site;
    no_atg;
    id_resp_pole;
    id_don_ordre;
    pu;
    date_debut_prest;
    date_fin_prest;
    etat_prest;
    site_sg;
    id_commercial_open;
    top_atg_atu;
    date_creation;
    id_utilisateur_creation;
    date_maj;
    utilisateur_maj;
}
